version: "3"

services:
  xray:
    image: teddysun/xray
    ports:
      - "62789:62789"
      - "1000:1000"
    restart: always
    volumes:
      - ./xray:/etc/xray
      - ./logs/xray:/logs
      - ${SSL_PATH}:/ssl

  shiray:
    build:
      context: src
      dockerfile: Dockerfile
    depends_on:
      - xray