version: "3.8"

services:
  xray:
    deploy:
      replicas: 1
    container_name: xray
    image: teddysun/xray
    ports:
      - "8443:3000" # exposed
    restart: always
    volumes:
      - ./xray:/etc/xray
      - ./logs/xray:/logs
      - ${SSL_PATH:-/ssl}:/ssl
    networks:
      internal:

  shiray:
    container_name: shiray
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config.json:/code/config.json
    ports:
      - "25857:22"
    depends_on:
      - xray
    networks:
      internal:

networks:
  internal: