version: "3"

services:
  xray:
    image: teddysun/xray
    ports:
#      - "62789:62789" not exposed
      - "443:443" # exposed
    restart: always
    volumes:
      - ./xray:/etc/xray
      - ./logs/xray:/logs
      - ${SSL_PATH}:/ssl
    networks:
      internal:

  shiray:
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - xray
    networks:
      internal:

networks:
  internal: