version: "3"

services:
  xray:
    container_name: xray
    image: teddysun/xray
    ports:
#      - "62789:62789" not exposed
      - "443:443" # exposed
    restart: always
    volumes:
      - ./xray:/etc/xray
      - ./logs/xray:/logs
      - ${SSL_PATH:-/ssl}:/ssl
    networks:
      internal:

  shiray:
    container_name: shiray
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "25857:22"
    depends_on:
      - xray
    networks:
      internal:

networks:
  internal: